#AQUI PUEDES PRACTICAR LOS CONSEPTOS BÁSICOS
#ANTERIORMENTE VISTOS EN LA SESIÓN 2.1
#EXISTE UN ARTÍCULO SOBRE EL USO DE PRINT EN PYTHON
#QUE TE PUEDE SERVIR DE REFERENCIA:

#https://realpython.com/python-print/

#PRACTICAR ESDE AQUÍ HACIA ABAJO

# imprime ello world en la consola
print ("hello world")
